# Generated by Django 4.1.5 on 2024-01-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_address_delete_userbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
