# Generated by Django 4.1.5 on 2024-01-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_customer_id_address_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='address_line2',
        ),
    ]
