# Generated by Django 4.1.5 on 2024-02-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_address_line_1_address_address_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
